version: "3.7"
services:
  reverse-proxy:
    # Pull the latest version of the reverse-proxy service
    image: ${ORG_NAME}/${ESTUARY_REVERSE_PROXY_TAGNAME}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - estuary-main

  estuary-main:
    # Pull the latest version of the estuary-main service
    image: ${ORG_NAME}/${ESTUARY_MAIN_TAGNAME}
    ports:
      - "3004:3004"
      - "3004:3004/udp"
volumes:
  estuary: