version: "3"
services:
  estuary-main:
    build:
      context: ./estuary-main
      dockerfile: Dockerfile
    volumes:
      - estuary:/usr/estuary/private
    environment:
      - ESTUARY_DATABASE=sqlite=/usr/src/estuary/data/estuary.db
      - ESTUARY_DATADIR=/usr/src/estuary/data/
      - ESTUARY_API_LISTEN=0.0.0.0:3004
      - FULLNODE_API_INFO=ws://lotus-node:1234
      - ESTUARY_HOSTNAME=http://estuary-main:3004
      - ESTUARY_USER=test
      - ESTUARY_PASSWORD=MyPassword123
    ports:
      - "3004:3004"
      - "3004:3004/udp"
    depends_on:
      - lotus-node
  
  estuary-shuttle:
    build:
      context: ./estuary-shuttle
      dockerfile: Dockerfile
    depends_on:
      - estuary-main
    ports:
      - "3005:3005"
      - "3005:3005/udp"
    environment:
      - ESTUARY_HOSTNAME=estuary-main:3004
    volumes:
      - estuary:/usr/estuary/private
  
  estuary-www:
    build:
      context: ./estuary-www
      dockerfile: Dockerfile
    environment:
      - ESTUARY_API=http://estuary-main:3004
    ports:
      - "4444:4444"
    depends_on:
      - estuary-main
    volumes:
      - estuary:/usr/estuary/private
    
  lotus-node:
    build:
      context: ./lotus
      dockerfile: Dockerfile

volumes:
  estuary:

networks: 
  default: 
    name: estuary-local-net
