version: "3"
services:
  estuary-main:
    build:
      context: ./estuary
      dockerfile: Dockerfile
    image: estuary-main:latest
    ports:
      - 3004:3004
    env_file:
      - ./.env 
networks: 
  default: 
    external: 
      name: estuary-local-net
